spring:
  application:
    name: user_center

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_center?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456

server:
  port: 8080
  address: 0.0.0.0   # ⭐ 强烈建议加

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
