spring:
  application:
    name:user-center

  datasource: # ???????? MySQL?
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8080
